import './globals.css'

const SmoothPageScroll = require('smooth-page-scroll');
 typeof window === 'location' && SmoothPageScroll.install();

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className='scroll-smooth'>{children}</body>
    </html>
  )
}
